### ISSUE TITLE
Signup or Demo User?

### ISSUE THREAD

**Issue by hariacharya80** [jmagrippis/nextjs-dashboard#2]
What if we have a signup feature too, this way new audience can view the entire dashboard.

**Comment by jmagrippis** [comment]
Hey Hari, thanks for being around in the livestream too!

Signup would be a cool feature, and necessary for most real apps, but I won't add it for now, as it's a few more things to worry about! Like people being too naughty and adding a million invoices, or deleting all of them etc 😅 then you'd need user roles, access control for who can do what, not to mention user flows for password recovery / resets!

So, for now, we can imagine this is an invite-only app, and you can use these demo credentials to checkout out the deployed dashboard:

```
email: user@nextmail.com
password: @nextjs
```

It's a bit easier for me to reset the DB and change the passwords if it comes to that, without a real signup flow live 🙂

You may want to checkout the signup flow in a real app I'm maintaining and adding to week by week!

https://johnnify.com/
& the code: https://github.com/jmagrippis/johnnify

I'm more likely to implement features you suggest over there 😄

Thanks again for raising this!

**Comment by hariacharya80** [comment]
Oh, thank you so much for your response. I have seen the dashboard and I loved it. Thanks for sharing this.
